### ISSUE TITLE
Neuronify på mac

### ISSUE THREAD

**Issue by Neurocket** [CINPLA/neuronify#115]
Digger appen dere har lagd!
Jeg prøvde neuronify på macen min hjemme i dag og har noen kommentarer:

1. Verken voltmeteret eller firing rate plot grafen viser noen spikes eller spenningsendringer.
Dette fungerte fint på Windows maskinen på jobben.
2. Angående "Types of inhibition" eksempelet.
Jeg tror "presynaptic inhibition" tradisjonelt har beskrevet 
inhibisjon direkte på den presynaptiske terminalen. 
Dvs, f.eks når GABA slippes fri fra en celle og binder GABA reseptorer som sitter i de presynaptiske terminalene til en annen celle.
Slik figuren er nå presenteres presynaptisk inhibisjon som et tilfelle der 
GABA frislippes ved cellekroppen som deretter hemmer nedstrøms synapser. 
Det er mulig modelleringsverdenen har en annen 
definisjon av presynaptisk inhibisjon så det er ikke sikkert dette er et problem.

-mattis

**Comment by miladh** [comment]
Takk for kommentarene Mattis!

Mac versjonen som ligger ute nå er en eldre versjon (v0.92) sammenlignet med nyeste versjonen for windows, ubuntu og google play (v0.93). Mulig problemene du har med voltmeter og rate plot fikser seg med nyeste versjonen.

Når det gjelder "Types of inhibition" eksemplet så er jeg helt enig med deg. Det er vanskelig å illustrere presynaptic inhibition med modellen vi bruker, så vi valgte å fjerne dette eksemplet i den nyeste versjonen.

Vi skal prøve å få lagt ut en nyere versjon av Neuronify for mac også veldig snart.

**Comment by dragly** [comment]
Takk for de hyggelige tilbakemeldingene, Mattis!

Hvilken versjon av Mac OS X bruker du? Jeg vet vi hadde problemer med grafer i 10.9 som ble fikset da brukeren oppgraderte helt til 10.11. Det viste seg å være en eldre versjon av grafikkdriverne som forårsaket problemet. Jeg mistenker at det kan være samme problem hos deg.

**Comment by Neurocket** [comment]
Hei, jeg har OS X 10.9.5 så det kan sikkert skyldes gammel versjon ja.
