### ISSUE TITLE
Speaker icon is invisible on mac

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#123]

**Comment by dragly** [comment]
A rename can automatically happen if the git repo is in a Dropbox folder. Dropbox will often revert the file name case if it changes between two commits. An easy fix is just to rename the file completely (loud-speaker.png instead of LoudSpeaker.png and Loudspeaker.png).

**Comment by andreavs** [comment]
This appears to be fixed now. Unclear which commit (not that important).
