### ISSUE TITLE
Hitboxes for connecting things are misplaced

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#125]
When attempting to connect two neurons (or any other item), if I try to drag the synapse to the right half of the receiving neuron, it will not attach. If i try to place it slightly outside the neuron on the left side, it will attach. 

This has only been tested on mac.

**Comment by miladh** [comment]
We don't have this problem on Ubuntu and Android

**Comment by andeplane** [comment]
I will test this on my mac tomorrow.

**Comment by miladh** [comment]
Tested on mac. It works.
