### ISSUE TITLE
Hard to select the correct connection when multiple connections are on top of each other

### ISSUE THREAD

**Issue by dragly** [CINPLA/neuronify#148]
Can be solved by setting the latest selected's z value to something lower than the current lowest z value.

**Comment by miladh** [comment]
Added latestZ in Neuronify.qml (f2b711cd947a0d47a201a5b55e3580b744e41e87), but we still need to shift the mouseArea for curved connections.

**Comment by dragly** [comment]
Offset edges in 7a28bb1db8d365ba09832b7ee59f7bcd28aeaccd. Consider this fixed now.
