### ISSUE TITLE
Tapping a touch detector on a mac with the track pad does not make it fire

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#150]
Not sure if bug or feature. Tested on macOS Sierra. Tapping selects the detector, but does not make it fire. Pressing the mouse button works

**Comment by dragly** [comment]
That is strange, I had a similar problem and fixed it one of my machines, but that fix doesn't appear to have been pushed.

Tried to fix it again now, in b1b8125. Can you test the new dmg when it gets published here?

https://github.com/CINPLA/neuronify/releases/tag/v0.94-touchsensor-test

**Comment by andeplane** [comment]
I tested on my Mac. Tapping fires always with the fix. With the previous version it fired sometimes with tap also, but not always.

**Comment by andreavs** [comment]
Confirmed working on macOS Sierra. Nice job!
