### ISSUE TITLE
Latest release does not work when newest qtcreator is not installed 

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#178]
Andreass-MacBook-Pro:MacOS andreasvavangsolbra$ ./Neuronify 
Neuronify version "v1.2.4-0-gd0676f2" started at 1498210544317
Verifying existense of QUrl("file:///Users/andreasvavangsolbra/Library/Preferences/Ovilab/Neuronify/savedata")
Verifying existense of QUrl("file:///Users/andreasvavangsolbra/Library/Application Support/Ovilab/Neuronify/community")
QQmlApplicationEngine failed to load component
qrc:///qml/main.qml:5 module "QtQuick.Controls" version 2.1 is not installed

**Comment by andeplane** [comment]
With the latest release, we only use QtQuick.Controls 2.0 so this should be resolved now.

I have testet the newest files from https://github.com/CINPLA/neuronify/releases/tag/v1.2.5 which both worked (both installer pkg and dmg). Can you verify @andreavs ?
