### ISSUE TITLE
Add "select all" button to measurement objects

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#28]
Such a button would be useful.

**Comment by andreavs** [comment]
Has been added to voltmeter. Might want to put the code in a separate QML object

**Comment by dragly** [comment]
API changes broke the current implementation in Voltmeter. Adding to a separate QML object is a good idea.

**Comment by dragly** [comment]
Dropping this for now. It is a bit easier to connect objects now because the connectors are visible when hovering items. We could also add back the "Connect multiple" mode where each clicked item is connected to the current item.
