### ISSUE TITLE
zooming with trackpad is unintuitive on mac

### ISSUE THREAD

**Issue by andreavs** [CINPLA/neuronify#79]
zooming by using the trackpad zooms in on the upper left corner of the screen. Should be either center or mouse position (preferably the latter).

**Comment by dragly** [comment]
Do you mean the two finger pinch-to-zoom[1] or two finger scroll while pressing the command key[2]?

The pinch-to-zoom is controlled by the PinchArea. The scroll-to-zoom is controlled by the MouseArea. Both should be centered properly. I think we concluded that this was a macOS-specific issue when we last discussed it. We should test the PinchArea+MouseArea setup in a smaller dummy project. I guess the problem might be that pinchStart.x and pinchStart.y are not set properly on macOS.

https://github.com/CINPLA/neuronify/blob/10dbe116b4fa8462e3389927d7407f9b22f6c7eb/qml/Neuronify.qml#L609-L721

[1]
![Pinch-to-zoom](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macbookair/trackpad-pinch_to_zoom.png)
[2]
![Scroll-to-zoom](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macbookair/trackpad-two_finger_scroll.png)

**Comment by dragly** [comment]
Tested on a Mac and it works as expected with both two-finger scroll and pinch-to-zoom in the latest version. This was probably fixed while we targeted iOS or in Qt itself.

**Comment by andreavs** [comment]
Confirmed as working on macOS sierra as well
