### ISSUE TITLE
Disable calculation in Retina if there is no camera present

### ISSUE THREAD

**Issue by dragly** [CINPLA/neuronify#84]
Currently the simulation runs slower on low performance hardware (Windows 10 in VirtualBox) when the Retina is added, even if no camera is present.

**Comment by dragly** [comment]
Isn't this fixed already?  @miladh

**Comment by miladh** [comment]
Firing rate is not calculated when RetinaEngine::receivedImage() is not called, which is the case when no camera is found/camera is busy. 
In addition, in RetinaEngine::stepEvent we check the size of m_stim. If 0, no additional calculations are made (such as sample a random number etc)
