### ISSUE TITLE
Spiking animations disappear

### ISSUE THREAD

**Issue by simetenn** [CINPLA/neuronify#96]
When the spiking is too fast the spiking dot disappear when a new spiking animation begins.

**Comment by dragly** [comment]
Needs to be fixed using either a) many preloaded objects to animate or b) dynamic creation and deletion of such objects.

Both introduces performance issues and code complexity. I suggest we postpone this until we have a more elegant solution.

Another option is to use particle effects instead, as particles are much cheaper (albeit less controllable).
