### ISSUE TITLE
Using back button on android crashes neuronify

### ISSUE THREAD

**Issue by simetenn** [CINPLA/neuronify#99]

**Comment by dragly** [comment]
Can be fixed by attaching to the Keys.onPressed event. Something like in Atomify: https://github.com/ComputationalPhysics/molecules/blob/master/qml/Molecules.qml#L437-L473

```qml
    Keys.onPressed: {
        if(event.key === Qt.Key_Back) {
            if(dashboard.revealed) {
                dashboard.revealed = false
                event.accepted = true
            } else if(mainMenu.revealed) {
                mainMenu.revealed = false
                event.accepted = true
            } else {
                console.log("Nothing to hide, quitting because back button pressed?")
            }
        }
    }
```

**Comment by dragly** [comment]
Note that the above solution requires that the item has the active focus. This is sometimes not the case and it can be cumbersome to ensure that it has the focus at all times. We should rather follow the pattern described in [this SO post](http://stackoverflow.com/a/30052804/632150), which is to add onClosing to the ApplicationWindow:

`onClosing: {
    close.accepted = false
}`
